---
default:
  image: docker-registry.eccenca.com/eccenca-python:v3.13.8
  # all jobs can be interrupted in case a new commit is pushed
  interruptible: true
  before_script:
    - uv tool install --reinstall cmem-cmemc@26.1.0rc3

variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - test
  - build
  - publish

check:
  stage: test
  resource_group: testing-server
  script:
    - task check

build:
  stage: build
  needs:
    - check
  script:
    - task build
  artifacts:
    when: always
    paths:
      - dist/*.*

publish:
  stage: publish
  only:
    - main
    - master
  needs:
    - build
  allow_failure: true
  script:
    - task publish

